export { default as Hero } from './Hero'
export { default as General } from './General'
export { default as Orders } from './Orders'
export { default as Favorites } from './Favorites'
export { default as ProductReviews } from './ProductReviews'
export { default as UserSubscriptions } from './UserSubscriptions'
