export { default as Content } from './Content'
export { default as Hero } from './Hero'
export { default as SidebarInfo } from './SidebarInfo'
export { default as SidebarNewsletter } from './SidebarNewsletter'
export { default as BrandProducts } from './BrandProducts'
